---
title: "Figure2 glycolysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(data.table)
require(tidyverse)
require(msigdbr)
require(ggpubr)
```


```{r}
H_gene_sets = msigdbr(species = "Homo sapiens")
glycolysis_sets = H_gene_sets %>%
  filter(grepl("GLYCOLYSIS", gs_name, ignore.case = TRUE))

unique(glycolysis_sets$gs_name)
glycolysis_gene_list = glycolysis_sets %>%
  group_by(gs_name) %>%
  summarise(genes = list(unique(gene_symbol))) %>%
  deframe()
```


# Module score

```{r}
require(qs)
require(Seurat)
# Load data
scrna = qread("../../data/DtST.qs")
scrna_meta = as.data.table(scrna@meta.data)

sample_meta = fread("../../data/sample_meta.csv")
sample_meta[, treatment := gsub("HKBCG", "BCG", treatment)]

id_map = fread("../../data/sample_scrna_id_map.csv", header = T)
all(id_map$samplemeta_sampleID == id_map$scrna_sampleID)
sample_meta[id_map, on = c("sampleID" = "samplemeta_sampleID"), scrna_DisplayName := i.scrna_DisplayName]
sample_meta[, select_sample := T]

scrna_meta[, tissue := toupper(tissue)]
scrna_meta[, tag := rownames(scrna@meta.data)]

scrna_meta = sample_meta[scrna_meta, on = c("scrna_DisplayName" = "DisplayName"),]
all(scrna_meta$tag == colnames(scrna))
unique(scrna_meta$set)

scrna_meta = scrna_meta[!is.na(set), ]

scrna = scrna[, scrna_meta$tag]
all(colnames(scrna) == scrna_meta$tag)

# add variables from experiment meta data
scrna$set = scrna_meta[, set]
scrna$apoe4_carrier = scrna_meta[, apoe4_carrier]
scrna$sex1m = scrna_meta[, sex1m]
scrna$km_ptau181_div_ab42 = scrna_meta[, km_ptau181_div_ab42]
scrna$moca_mci_ad = scrna_meta[, moca_mci_ad]
scrna$a75_il6_lps = scrna_meta[, a75_il6_lps]
scrna$gt1_lps = scrna_meta[, gt1_lps]
scrna$disease = ifelse(scrna$km_ptau181_div_ab42, 'AD', 'Healthy')
```

```{r}
mono_scrna = scrna[, scrna$predicted.celltype.l1 == "Mono"]
cd4T_scrna = scrna[, scrna$predicted.celltype.l1 == "CD4 T"]
cd8T_scrna = scrna[, scrna$predicted.celltype.l1 == "CD8 T"]

dotplot = function(sets, sel_scrna){
  library(ggplot2)
  p = DotPlot(
    sel_scrna, 
    features = paste0(sets, "1"), 
    group.by = "timepoint",
    scale = T
  )
  
  # Custom color scale: blue → yellow → red centered at 0
  p = p + 
    labs(y = "Time (month)") +
    scale_color_gradientn(
      colors = c("#5B99C2", "#ffedda", "#F95454"),
      values = scales::rescale(c(min(p$data$avg.exp.scaled), 0, max(p$data$avg.exp.scaled))),
      limits = c(min(p$data$avg.exp.scaled), max(p$data$avg.exp.scaled)),
      name = "Score"
    ) +
    scale_x_discrete(labels = sets) +
    scale_size(range = c(1, 6), limits = c(10, 100), name = "% Expressed") +
    theme(
      panel.grid = element_blank(),
      panel.border = element_rect(color = "black", fill = NA, linewidth = 0.7),
      axis.text = element_text(color = "black", size = 10),
      axis.title = element_text(color = "black", size = 11),
      strip.placement = "outside",
      strip.text.x = element_text(size = 10),
      axis.ticks = element_line(color = "black", linewidth = 0.5),
      axis.ticks.length = unit(0.08, "cm"),
      axis.minor.ticks.length.y = unit(0.05, "cm")
    )  + coord_flip()

  return(p)
}
```

## Monocytes

```{r}
mono_sets = unique(glycolysis_sets$gs_name)[c(3:4, 6:10, 12:13)]
mono_scrna$timepoint = factor(mono_scrna$time, levels = c(0, 3, 12))

for (sel_set in mono_sets) {
  message("Processing ", sel_set)
  set_genes = glycolysis_gene_list[[sel_set]]
  sel_genes = intersect(set_genes, rownames(scrna))
  if(length(sel_genes) != 0){
    mono_scrna = AddModuleScore(mono_scrna, list(sel_genes), name = sel_set)
  }else{
    message("No intersect gene found.")
    message("Number of sel_genes: ", length(sel_genes))
    next
  }
}


# Basal
mono_sets = unique(glycolysis_sets$gs_name)[c(3:4, 6:10, 12:13)]
dotplot(sel_scrna = mono_scrna[, mono_scrna$set == "CSF - Basal (BCG effect) set"], sets = mono_sets)
ggsave("../outputs/Mono_glycolysis_basal.png", dpi = 300, height = 4.5, width = 10.3)


mono_sets = unique(glycolysis_sets$gs_name)[c(3:4, 6:7, 9:10, 12:13)]
dotplot(sel_scrna = mono_scrna[, mono_scrna$set == "CSF - Basal (BCG effect) set"], sets = mono_sets)
ggsave("../outputs/Mono_glycolysis_basal_noreactome.png", dpi = 300, height = 4.5, width = 8.3)


# CSF Stim - BCG
mono_sets = unique(glycolysis_sets$gs_name)[c(3:4, 6:10, 12:13)]
dotplot(sel_scrna = mono_scrna[, mono_scrna$set == "CSF - Stim sample set" & mono_scrna$treatment == "BCG"], sets = mono_sets)
ggsave("../outputs/Mono_glycolysis_CSFStim_BCG.png", dpi = 300, height = 4.5, width = 10.3)

mono_sets = unique(glycolysis_sets$gs_name)[c(3:4, 6:7, 9:10, 12:13)]
dotplot(sel_scrna = mono_scrna[, mono_scrna$set == "CSF - Stim sample set" & mono_scrna$treatment == "BCG"], sets = mono_sets)
ggsave("../outputs/Mono_glycolysis_CSFStim_BCG_noreactome.png", dpi = 300, height = 4.5, width = 8.3)

# CSF Stim - LPS
mono_sets = unique(glycolysis_sets$gs_name)[c(3:4, 6:10, 12:13)]
dotplot(sel_scrna = mono_scrna[, mono_scrna$set == "CSF - Stim sample set" & mono_scrna$treatment == "LPS"], sets = mono_sets)
ggsave("../outputs/Mono_glycolysis_CSFStim_LPS.png", dpi = 300, height = 4.5, width = 10.3)

mono_sets = unique(glycolysis_sets$gs_name)[c(3:4, 6:7, 9:10, 12:13)]
dotplot(sel_scrna = mono_scrna[, mono_scrna$set == "CSF - Stim sample set" & mono_scrna$treatment == "LPS"], sets = mono_sets)
ggsave("../outputs/Mono_glycolysis_CSFStim_LPS_noreactome.png", dpi = 300, height = 4.5, width = 8.3)


# PBMC Stim - BCG
mono_sets = unique(glycolysis_sets$gs_name)[c(3:4, 6:10, 12:13)]
dotplot(sel_scrna = mono_scrna[, mono_scrna$set == "PBMC - Stim sample set" & mono_scrna$treatment == "BCG"], sets = mono_sets)
ggsave("../outputs/Mono_glycolysis_PBMCStim_BCG.png", dpi = 300, height = 4.5, width = 10.3)

mono_sets = unique(glycolysis_sets$gs_name)[c(3:4, 6:7, 9:10, 12:13)]
dotplot(sel_scrna = mono_scrna[, mono_scrna$set == "PBMC - Stim sample set" & mono_scrna$treatment == "BCG"], sets = mono_sets)
ggsave("../outputs/Mono_glycolysis_PBMCStim_BCG_noreactome.png", dpi = 300, height = 4.5, width = 8.3)

# CSF Stim - LPS
mono_sets = unique(glycolysis_sets$gs_name)[c(3:4, 6:10, 12:13)]
dotplot(sel_scrna = mono_scrna[, mono_scrna$set == "PBMC - Stim sample set" & mono_scrna$treatment == "LPS"], sets = mono_sets)
ggsave("../outputs/Mono_glycolysis_PBMCStim_LPS.png", dpi = 300, height = 4.5, width = 10.3)

mono_sets = unique(glycolysis_sets$gs_name)[c(3:4, 6:7, 9:10, 12:13)]
dotplot(sel_scrna = mono_scrna[, mono_scrna$set == "PBMC - Stim sample set" & mono_scrna$treatment == "LPS"], sets = mono_sets)
ggsave("../outputs/Mono_glycolysis_PBMCStim_LPS_noreactome.png", dpi = 300, height = 4.5, width = 8.3)
```


```{r}
compare_module_scores = function(
    sel_scrna, sets, sel_celltype, sel_set, sel_treatment
) {
  
  r = lapply(sets, function(sel_gset){
    df = FetchData(
      sel_scrna[, sel_scrna$set == sel_set & sel_scrna$treatment == sel_treatment], 
      vars = c("timepoint", paste0(sel_gset, "1"))
    )
    r1 = wilcox.test(
      formula(paste0(sel_gset, "1 ~ timepoint")), 
      data = df %>% filter(timepoint %in% c(0, 3))
    )
    r2 = wilcox.test(
      formula(paste0(sel_gset, "1 ~ timepoint")), 
      data = df %>% filter(timepoint %in% c(0, 12))
    )
    r3 = wilcox.test(
      formula(paste0(sel_gset, "1 ~ timepoint")), 
      data = df %>% filter(timepoint %in% c(0, 3))
    )
    return(
      rbind(
        data.table(
          geneset = sel_gset, 
          p.value = r1$p.value, 
          celltype = sel_celltype,
          set = sel_set,
          treatment = sel_treatment,
          comparison = c("3_vs_0")
        ),
        data.table(
          geneset = sel_gset, 
          p.value = r2$p.value, 
          celltype = sel_celltype,
          set = sel_set,
          treatment = sel_treatment,
          comparison = c("12_vs_0")
        ),
        data.table(
          geneset = sel_gset, 
          p.value = r3$p.value, 
          celltype = sel_celltype,
          set = sel_set,
          treatment = sel_treatment,
          comparison = c("12_vs_3")
        )
      )
     )
  })
  
  return(Reduce(rbind, r))
}

score_comparisions = rbind(
  compare_module_scores(
      sel_scrna = mono_scrna, 
      sets = mono_sets, 
      sel_celltype = "Mono", 
      sel_set = "CSF - Stim sample set", 
      sel_treatment = "BCG"
  ),
  compare_module_scores(
      sel_scrna = mono_scrna, 
      sets = mono_sets, 
      sel_celltype = "Mono", 
      sel_set = "PBMC - Stim sample set", 
      sel_treatment = "BCG"
  ),
  compare_module_scores(
      sel_scrna = mono_scrna, 
      sets = mono_sets, 
      sel_celltype = "Mono", 
      sel_set = "CSF - Stim sample set", 
      sel_treatment = "LPS"
  ),
  compare_module_scores(
      sel_scrna = mono_scrna, 
      sets = mono_sets, 
      sel_celltype = "Mono", 
      sel_set = "PBMC - Stim sample set", 
      sel_treatment = "LPS"
  ),
  compare_module_scores(
      sel_scrna = mono_scrna, 
      sets = mono_sets, 
      sel_celltype = "Mono", 
      sel_set = "CSF - Basal (BCG effect) set", 
      sel_treatment = "Ctrl"
  ),
  compare_module_scores(
      sel_scrna = mono_scrna, 
      sets = mono_sets, 
      sel_celltype = "Mono", 
      sel_set = "CSF - Basal (BCG effect) set", 
      sel_treatment = "Ctrl"
  )
)
fwrite(score_comparisions, file = "../outputs/glycolysis_score_comparisons_Mono.csv")
```



## CD4 T

```{r}
cd4T_sets = unique(glycolysis_sets$gs_name)[c(1,4, 6:10, 12:13)]
cd4T_scrna$timepoint = factor(cd4T_scrna$time, levels = c(0, 3, 12))

for (sel_set in cd4T_sets) {
  message("Processing ", sel_set)
  set_genes = glycolysis_gene_list[[sel_set]]
  sel_genes = intersect(set_genes, rownames(scrna))
  if(length(sel_genes) != 0){
    cd4T_scrna = AddModuleScore(cd4T_scrna, list(sel_genes), name = sel_set)
  }else{
    message("No intersect gene found.")
    message("Number of sel_genes: ", length(sel_genes))
    next
  }
  
}

# Basal
cd4T_sets = unique(glycolysis_sets$gs_name)[c(1,4, 6:10, 12:13)]
dotplot(sel_scrna = cd4T_scrna[, cd4T_scrna$set == "CSF - Basal (BCG effect) set"], sets = cd4T_sets)
ggsave("../outputs/CD4T_glycolysis_basal.png", dpi = 300, height = 4.5, width = 10.3)

cd4T_sets = unique(glycolysis_sets$gs_name)[c(1,4, 6:7, 9:10, 12:13)]
dotplot(sel_scrna = cd4T_scrna[, cd4T_scrna$set == "CSF - Basal (BCG effect) set"], sets = cd4T_sets)
ggsave("../outputs/CD4T_glycolysis_basal_noreactome.png", dpi = 300, height = 4.5, width = 8.3)
```





## CD8 T

```{r}
cd8T_sets = unique(glycolysis_sets$gs_name)[c(2,4, 6:10, 12:13)]
cd8T_scrna$timepoint = factor(cd8T_scrna$time, levels = c(0, 3, 12))

for (sel_set in cd8T_sets) {
  message("Processing ", sel_set)
  set_genes = glycolysis_gene_list[[sel_set]]
  sel_genes = intersect(set_genes, rownames(scrna))
  if(length(sel_genes) != 0){
    cd8T_scrna = AddModuleScore(cd8T_scrna, list(sel_genes), name = sel_set)
  }else{
    message("No intersect gene found.")
    message("Number of sel_genes: ", length(sel_genes))
    next
  }
  
}

# Basal
cd8T_sets = unique(glycolysis_sets$gs_name)[c(2,4, 6:10, 12:13)]
dotplot(sel_scrna = cd8T_scrna[, cd8T_scrna$set == "CSF - Basal (BCG effect) set"], sets = cd8T_sets)
ggsave("../outputs/CD8T_glycolysis_basal.png", dpi = 300, height = 4.5, width = 10.3)

cd8T_sets = unique(glycolysis_sets$gs_name)[c(2, 4, 6:7, 9:10, 12:13)]
dotplot(sel_scrna = cd8T_scrna[, cd8T_scrna$set == "CSF - Basal (BCG effect) set"], sets = cd4T_sets)
ggsave("../outputs/CD8T_glycolysis_basal_noreactome.png", dpi = 300, height = 4.5, width = 8.3)
```


```{r}
cd4T_sets = unique(glycolysis_sets$gs_name)[c(1,4, 6:10, 12:13)]
cd8T_sets = unique(glycolysis_sets$gs_name)[c(1,4, 6:10, 12:13)]
score_comparisions_T = rbind(
  compare_module_scores(
      sel_scrna = cd4T_scrna, 
      sets = cd4T_sets, 
      sel_celltype = "CD4 T", 
      sel_set = "CSF - Basal (BCG effect) set", 
      sel_treatment = "Ctrl"
  ),
  compare_module_scores(
      sel_scrna = cd4T_scrna, 
      sets = cd4T_sets, 
      sel_celltype = "CD4 T", 
      sel_set = "CSF - Basal (BCG effect) set", 
      sel_treatment = "Ctrl"
  ),
  compare_module_scores(
      sel_scrna = cd8T_scrna, 
      sets = cd8T_sets, 
      sel_celltype = "CD8 T", 
      sel_set = "CSF - Basal (BCG effect) set", 
      sel_treatment = "Ctrl"
  ),
  compare_module_scores(
      sel_scrna = cd8T_scrna, 
      sets = cd8T_sets, 
      sel_celltype = "CD8 T", 
      sel_set = "CSF - Basal (BCG effect) set", 
      sel_treatment = "Ctrl"
  )
)
fwrite(score_comparisions_T, file = "../outputs/glycolysis_score_comparisons_Tcells.csv")
```




# Cell level figures
```{r}
calculate_avgexp = function(
  basal, sel_set, sel_celltype, gene_list, sample_meta
){
  sample_meta[, donor_time := paste(donor, time, sep = "_")]
  sel_genes = gene_list[[sel_set]]
  basal_ctype_dt = basal[
    gene_name %in% sel_genes, 
    c("gene_name", grep(paste0("^", sel_celltype), colnames(basal), value = T)), 
  with = F]
  basal_ctype_dt = melt(
    basal_ctype_dt, 
    id.vars = "gene_name", 
    variable.name = "ctype_donor_time", 
    value.name = "pseudocounts"
  )
  basal_ctype_dt[, donor_time := gsub(paste0(sel_celltype, "_"), "", ctype_donor_time)]
  sample_meta = sample_meta[, .(donor_time, apoe4_carrier, sex1m, donor, time, km_ptau181_div_ab42)] %>%
    unique() %>%
    .[
    data.table(donor_time = gsub(paste0(sel_celltype, "_"), "", basal_ctype_dt$donor_time)), 
    on = .(donor_time),
  ]
  basal_ctype_dt[, 
    c("time", "donor", "apoe4_carrier", "sex1m", "km_ptau181_div_ab42") := .(sample_meta$time, sample_meta$donor, sample_meta$apoe4_carrier, sample_meta$sex1m, sample_meta$km_ptau181_div_ab42)
  ]
  avg_dt = basal_ctype_dt[, .(avg_pseudocounts = mean(pseudocounts)), by = .(gene_name, km_ptau181_div_ab42, time)]
  return(avg_dt)
}


signature_analysis = function(
  basel, sel_set, sel_celltype, gene_list, sample_meta
){
    plot_dt = calculate_avgexp(
        basal, sel_set, sel_celltype, gene_list, sample_meta
      ) %>%
      filter(time %in% c(0, 12)) %>%
      mutate(
        time = factor(time, levels = c(0, 12)),
        AD_status = ifelse(km_ptau181_div_ab42, "AD", "non-AD")
      )
  
  
    # Split data by AD_status and run Wilcoxon tests
    pval_results = lapply(split(plot_dt, plot_dt$AD_status), function(df) {
      data.frame(
        AD_status = unique(df$AD_status),
        n_gene_0 = sum(df$time == 0),
        n_gene_12 = sum(df$time == 12),
        p_value = tryCatch(
          wilcox.test(avg_pseudocounts ~ time, data = df, exact = FALSE)$p.value,
          error = function(e) NA
        ),
        gene_set = sel_set,
        celltype = sel_celltype
      )
    }) %>% bind_rows() %>%
    mutate(
      signif_label = case_when(
        is.na(p_value) ~ "ns",
        p_value < 0.001 ~ "***",
        p_value < 0.01 ~ "**",
        p_value < 0.05 ~ "*",
        TRUE ~ "ns"
      )
    )
  
     # Merge significance into plot position info
    label_df <- plot_dt %>%
      group_by(AD_status, time) %>%
      summarise(y = max(avg_pseudocounts) + 0.1, .groups = "drop") %>%
      distinct(AD_status, .keep_all = TRUE) %>%
      left_join(pval_results[, c("AD_status", "signif_label")], by = "AD_status")
    
    # Create bracket data
    bracket_df <- plot_dt %>%
      group_by(AD_status) %>%
      summarise(
        y_bracket = max(avg_pseudocounts) + 0.3,
        x_start = 1, x_end = 2,
        .groups = "drop"
      ) %>%
      left_join(pval_results[, c("AD_status", "signif_label")], by = "AD_status")
    
    p = ggplot(plot_dt, aes(x = time, y = avg_pseudocounts, fill = AD_status)) +
      geom_violin(alpha = 0.3, width = 0.7, color = NA) +
      geom_boxplot(width = 0.2, outlier.shape = NA, color = "black", alpha = 0.6) +
      geom_line(aes(group = gene_name, color = AD_status), linewidth = 0.8, alpha = 0.2) +
      geom_point(aes(color = AD_status), size = 2, position = position_dodge(width = 0.8)) +
    
      # Bracket line
      geom_segment(
        data = bracket_df,
        aes(x = x_start, xend = x_end, y = y_bracket, yend = y_bracket),
        inherit.aes = FALSE
      ) +
      geom_segment(
        data = bracket_df,
        aes(x = x_start, xend = x_start, y = y_bracket, yend = y_bracket - 0.2),
        inherit.aes = FALSE
      ) +
      geom_segment(
        data = bracket_df,
        aes(x = x_end, xend = x_end, y = y_bracket, yend = y_bracket - 0.2),
        inherit.aes = FALSE
      ) +
      geom_text(
        data = bracket_df,
        aes(x = (x_start + x_end)/2, y = y_bracket + 0.34, label = signif_label),
        inherit.aes = FALSE,
        size = 5
      ) +
    
      # Styling
      scale_fill_manual(values = c("AD" = "#F95454", "non-AD" = "#5B99C2")) +
      scale_color_manual(values = c("AD" = "#F95454", "non-AD" = "#5B99C2")) +
      theme_minimal() +
      labs(
        x = "Time (months)",
        y = "Average Pseudocounts",
        title = stringr::str_wrap(gsub("_", " ", paste0(sel_celltype, ": ", sel_set)), width = 40),
        fill = "AD status",
        color = "AD status"
      ) +
      facet_grid(. ~ AD_status) +
      theme(
        strip.text = element_blank(),
        axis.text = element_text(size = 10, color = "black"),
        axis.title = element_text(size = 12),
        plot.title = element_text(size = 14, face = "bold", hjust = 0.5),
        legend.title = element_text(size = 11),
        legend.text = element_text(size = 10)
      ) +
      theme(
        panel.grid = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, linewidth = 1),
        axis.line = element_blank(),
        plot.background = element_rect(fill = "white", color = NA),
        axis.ticks = element_line(color = "black", linewidth = 0.5),
        axis.text = element_text(color = "black", size = 15),
        axis.title.y = element_text(face = "bold", size = 14),
        axis.title.x = element_text(face = "bold", size = 14, hjust = 0.5),
        axis.ticks.length = unit(0.15, "cm"),
        axis.minor.ticks.length.x = unit(0.05, "cm"),
        axis.minor.ticks.length.y = unit(0.05, "cm")
      )
    
    return(list(p = p, results = pval_results))
}



# basal = fread(file.path("../source_data", "pseudobulk_counts_vst_basal_CSF.csv"))
# dcast(basal_ctype_dt, ctype_donor_time ~ gene_name, value.var = "pseudocounts")
sample_meta = fread(file.path("../source_data", "sample_meta.csv"))

r_celltypes = lapply(c("CD4 T", "Mono", "CD8 T"), function(sel_celltype){
  r_per_ctype = lapply(names(glycolysis_gene_list), function(sel_set){
    return(signature_analysis(
      basel, 
      sel_set, 
      sel_celltype, 
      gene_list = glycolysis_gene_list, 
      sample_meta
    ))
  })
  dt_per_ctype = Reduce(rbind, lapply(r_per_ctype, function(x) x$results))
  ps_per_ctype = lapply(r_per_ctype, function(x) x$p)
  p = ggarrange(plotlist = ps_per_ctype, ncol = 3, nrow = 5, common.legend = T, align = "hv")
  return(list(ps = ps_per_ctype, dt = dt_per_ctype, p = p))
})

glycolysis_results = Reduce(rbind, lapply(r_celltypes, function(x) x$dt))
names(r_celltypes) = c("CD4 T", "Mono", "CD8 T")
glycolysis_p = lapply(names(r_celltypes), function(sel_ctype){
  x = r_celltypes[[sel_ctype]]
  ggsave(paste0("../outputs/", sel_ctype, "_glycolysis_signature.png"), x$p, width = 18, height = 18)
  return(x$p)
})

fwrite(glycolysis_results, file = file.path("..", "outputs", "glycolysis_results.csv"))

```



# PCA

```{r}
#sel_set = unique(glycolysis_sets$gs_name)[3]
sel_set = unique(glycolysis_sets$gs_name)[1]
sel_set = unique(glycolysis_sets$gs_name)[4]
sel_genes = glycolysis_gene_list[[sel_set]]
sel_celltype = "CD4 T"


sample_meta = fread(file.path("../source_data", "sample_meta.csv"))
sample_meta[, donor_time := paste(donor, time, sep = "_")]

pca_plots = function(sel_set, sel_genes, sel_celltype, sample_meta){
  basal_dt = basal[gene_name %in% sel_genes] %>%
  as.data.frame() %>%
  column_to_rownames("gene_name")
basal_ctype_dt = basal_dt[, grep(paste0("^", sel_celltype), colnames(basal_dt))]
basal_ctype_dt = t(basal_ctype_dt)
pca_result = prcomp(basal_ctype_dt, scale. = F)
pca_dt = as.data.frame(pca_result$x)

sample_meta = sample_meta[
  data.table(donor_time = gsub(paste0(sel_celltype, "_"), "", rownames(pca_dt))), 
    on = .(donor_time)
  ]
  all(sample_meta$donor_time == gsub(paste0(sel_celltype, "_"), "", rownames(pca_dt)))
  pca_dt$treatment = sample_meta$treatment
  pca_dt$time = sample_meta$time
  pca_dt$donor = sample_meta$donor
  
  ggplot(pca_dt, aes(PC1, PC2, color = as.character(time))) +
    geom_point()
  ggplot(pca_dt, aes(PC2, PC3, color = as.character(time))) +
    geom_point()
  ggplot(pca_dt, aes(PC3, PC4, color = as.character(time))) +
    geom_point()
  ggplot(pca_dt, aes(PC5, PC6, color = as.character(time))) +
    geom_point()
}

#basal = fread(file.path("../source_data", "pseudobulk_counts_vst_basal_CSF.csv"))
basal_dt = basal[gene_name %in% sel_genes] %>%
  as.data.frame() %>%
  column_to_rownames("gene_name")
basal_ctype_dt = basal_dt[, grep(paste0("^", sel_celltype), colnames(basal_dt))]
basal_ctype_dt = t(basal_ctype_dt)
pca_result = prcomp(basal_ctype_dt, scale. = F)
pca_dt = as.data.frame(pca_result$x)

sample_meta = sample_meta[
  data.table(donor_time = gsub(paste0(sel_celltype, "_"), "", rownames(pca_dt))), 
  on = .(donor_time)
]
all(sample_meta$donor_time == gsub(paste0(sel_celltype, "_"), "", rownames(pca_dt)))
pca_dt$treatment = sample_meta$treatment
pca_dt$time = sample_meta$time
pca_dt$donor = sample_meta$donor

ggplot(pca_dt, aes(PC1, PC2, color = as.character(time))) +
  geom_point()
ggplot(pca_dt, aes(PC2, PC3, color = as.character(time))) +
  geom_point()
ggplot(pca_dt, aes(PC3, PC4, color = as.character(time))) +
  geom_point()
ggplot(pca_dt, aes(PC5, PC6, color = as.character(time))) +
  geom_point()
```



